collection hard
Denive/DZ3 pull request #4
Opened 2018-05-12 08:56 UTC by Denive

2018-05-12 11:06 UTC, polikhill requested changes

2018-05-12 11:06 UTC, Pollypug commented on DZ3/ViewController.swift
> +        for x in 1..<a.count {
Лучше избавиться от переменные типа "а"

2018-05-12 11:20 UTC, polikhill approved these changes

2018-05-12 11:28 UTC, merged

2018-05-13 09:27 UTC, tungfam reviewed
гуд